# Generated by Django 4.2.16 on 2026-06-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('nick', models.CharField(blank=True, max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('postulante', 'Postulante'), ('suspendido', 'Suspendido'), ('honorario', 'Honorario')], default='activo', max_length=20)),
                ('rol', models.CharField(choices=[('capitan', 'Capitán'), ('tesorero', 'Tesorero'), ('integrante', 'Integrante'), ('postulante', 'Postulante'), ('invitado', 'Invitado')], default='integrante', max_length=20)),
                ('talla_polera', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='integrantes/fotos/')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integrante',
                'verbose_name_plural': 'Integrantes',
                'ordering': ['nombre'],
            },
        ),
    ]
