# Generated by Django 4.2.16 on 2026-06-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('pos_natal', 'Pos Natal'), ('postulante', 'Postulante'), ('suspendido', 'Suspendido'), ('honorario', 'Honorario')], default='activo', max_length=20),
        ),
    ]
