# Generated by Django 4.2.16 on 2026-06-07 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrantes', '0002_add_pos_natal_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrante', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema'),
        ),
    ]
