# Generated by Django 4.2.16 on 2026-06-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrantes', '0004_alter_integrante_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='rol',
            field=models.CharField(choices=[('admin', 'Admin'), ('TL', 'Team Leader'), ('presidente', 'Presidente'), ('vice', 'Vice Presidente'), ('secretario', 'Secretario'), ('tesorero', 'Tesorero'), ('player', 'Player'), ('postulante', 'Postulante'), ('invitado', 'Invitado')], default='integrante', max_length=20),
        ),
    ]
