# Generated by Django 4.2.16 on 2026-06-09 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0004_configuracioncuota'),
        ('integrantes', '0005_alter_integrante_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=0, max_digits=10)),
                ('proveedor', models.CharField(default='flow', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('orden_id', models.CharField(max_length=100, unique=True)),
                ('token_proveedor', models.CharField(blank=True, max_length=255)),
                ('url_pago', models.URLField(blank=True, max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('datos_respuesta', models.JSONField(default=dict)),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_online', to='integrantes.integrante')),
                ('mensualidades', models.ManyToManyField(blank=True, related_name='pagos_online', to='finanzas.mensualidad')),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pago_origen', to='finanzas.movimiento')),
            ],
            options={
                'verbose_name': 'Pago Online',
                'verbose_name_plural': 'Pagos Online',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
