# Generated by Django 4.2.16 on 2026-06-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('TL', 'Team Leader'), ('presidente', 'Presidente'), ('vice', 'Vice Presidente'), ('secretario', 'Secretario'), ('tesorero', 'Tesorero'), ('player', 'Player')], default='player', max_length=20),
        ),
    ]
