# Generated by Django 4.2.16 on 2026-06-01 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('entrenamiento', 'Entrenamiento'), ('partida', 'Partida'), ('campeonato', 'Campeonato'), ('reunion', 'Reunión'), ('actividad', 'Actividad Interna'), ('externo', 'Evento Externo')], max_length=20)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='programado', max_length=15)),
                ('imagen_destacada', models.ImageField(blank=True, null=True, upload_to='eventos/imagenes/')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('asistentes', models.ManyToManyField(blank=True, related_name='asistencias', to='integrantes.integrante')),
                ('convocados', models.ManyToManyField(blank=True, related_name='convocatorias', to='integrantes.integrante')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistio', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='eventos.evento')),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='integrantes.integrante')),
            ],
            options={
                'verbose_name': 'Participación',
                'verbose_name_plural': 'Participaciones',
                'ordering': ['-evento__fecha'],
                'unique_together': {('integrante', 'evento')},
            },
        ),
    ]
