# Generated by Django 4.2.16 on 2026-06-01 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrantes', '0001_initial'),
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='integrante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='integrantes.integrante'),
        ),
        migrations.AddField(
            model_name='mensualidad',
            name='integrante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensualidades', to='integrantes.integrante'),
        ),
        migrations.AddField(
            model_name='importacionarchivo',
            name='importado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deuda',
            name='integrante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to='integrantes.integrante'),
        ),
        migrations.AlterUniqueTogether(
            name='mensualidad',
            unique_together={('integrante', 'anio', 'mes')},
        ),
    ]
