# Generated by Django 4.2.16 on 2026-06-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciliacionExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('origen_archivo', models.CharField(max_length=300)),
                ('hcontable_caja_chica', models.DecimalField(decimal_places=0, default=0, help_text='H.CONTABLE!P7 — Total caja chica + mensualidades 2022', max_digits=12)),
                ('hcontable_donaciones', models.DecimalField(decimal_places=0, default=0, help_text='H.CONTABLE!P10 — Donaciones e ingresos', max_digits=12)),
                ('hcontable_gastos', models.DecimalField(decimal_places=0, default=0, help_text='H.CONTABLE!P13 — Total gastos históricos', max_digits=12)),
                ('hcontable_efectivo_extra', models.DecimalField(decimal_places=0, default=0, help_text='H.CONTABLE!L47 — Efectivo adicional', max_digits=12)),
                ('mensualidades_2023', models.DecimalField(decimal_places=0, default=0, help_text='MENSUALIDADES 2023!S34', max_digits=12)),
                ('rifa_total', models.DecimalField(decimal_places=0, default=0, help_text='RIFA!N36', max_digits=12)),
                ('mensualidades_2024', models.DecimalField(decimal_places=0, default=0, help_text='MENSUALIDADES 2024!S41', max_digits=12)),
                ('mensualidades_2025', models.DecimalField(decimal_places=0, default=0, help_text='MENSUALIDADES 2025!S35', max_digits=12)),
            ],
            options={
                'verbose_name': 'Conciliación Excel',
                'verbose_name_plural': 'Conciliaciones Excel',
                'ordering': ['-fecha_importacion'],
            },
        ),
    ]
