# Generated by Django 4.2.16 on 2026-06-01 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finanzas', '0003_conciliacionexcel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_cuota', models.DecimalField(decimal_places=0, default=5000, max_digits=10)),
                ('moneda', models.CharField(default='CLP', max_length=5)),
                ('vigencia_desde', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuracion de Cuota',
                'verbose_name_plural': 'Configuraciones de Cuota',
                'ordering': ['-vigencia_desde'],
            },
        ),
    ]
