# Generated by Django 4.2.16 on 2026-06-14 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_configuracioncuota'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=500)),
                ('cargo', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('abono', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('referencia_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('estado_conciliacion', models.CharField(choices=[('sin_conciliar', 'Sin conciliar'), ('conciliado', 'Conciliado'), ('ignorado', 'Ignorado')], default='sin_conciliar', max_length=15)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracto', to='finanzas.cuentabanco')),
                ('importacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.importacionarchivo')),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracto_origen', to='finanzas.movimiento')),
            ],
            options={
                'verbose_name': 'Extracto Bancario',
                'verbose_name_plural': 'Extractos Bancarios',
                'ordering': ['-fecha', '-fecha_importacion'],
            },
        ),
    ]
