# Generated by Django 4.2.16 on 2026-06-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_extracto_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='conciliacionexcel',
            name='saldo_p16',
            field=models.DecimalField(decimal_places=0, default=0, help_text='H.CONTABLE!P16 — Saldo real calculado por Excel', max_digits=12),
        ),
        migrations.AlterField(
            model_name='conciliacionexcel',
            name='hcontable_gastos',
            field=models.DecimalField(decimal_places=0, default=0, help_text='H.CONTABLE!G142 — Total gastos históricos', max_digits=12),
        ),
    ]
