# Generated by Django 4.2.16 on 2026-06-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_conciliacion_saldo_p16'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso'), ('donacion', 'Donación')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso'), ('donacion', 'Donación')], max_length=10),
        ),
    ]
