# Generated by Django 4.2.16 on 2026-06-01 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('noticias', '0001_initial'),
        ('galeria', '0001_initial'),
        ('integrantes', '0001_initial'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacioninstagram',
            name='noticia_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones_ig', to='noticias.noticia'),
        ),
        migrations.AddField(
            model_name='foto',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='galeria.album'),
        ),
        migrations.AddField(
            model_name='foto',
            name='integrantes_etiquetados',
            field=models.ManyToManyField(blank=True, related_name='fotos', to='integrantes.integrante'),
        ),
        migrations.AddField(
            model_name='album',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='eventos.evento'),
        ),
    ]
