# Generated by Django 4.2.16 on 2026-06-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacioninstagram',
            options={'ordering': ['-destacado', '-fecha_creacion'], 'verbose_name': 'Publicación Instagram', 'verbose_name_plural': 'Publicaciones Instagram'},
        ),
        migrations.AddField(
            model_name='publicacioninstagram',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
