# Generated by Django 4.2.16 on 2026-06-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.PositiveSmallIntegerField()),
                ('ciudad', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('nick', models.CharField(blank=True, max_length=60)),
                ('experiencia', models.TextField(blank=True)),
                ('tiene_equipo', models.BooleanField(default=False)),
                ('como_conocio', models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('amigo', 'Un amigo o conocido'), ('evento', 'En un evento de Airsoft'), ('internet', 'Búsqueda en internet'), ('otro', 'Otro')], max_length=20)),
                ('mensaje', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisando', 'En revisión'), ('en_prueba', 'Partida de prueba'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=15)),
                ('notas_admin', models.TextField(blank=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Postulación',
                'verbose_name_plural': 'Postulaciones',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
